# Generated by Django 4.0.2 on 2022-03-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(height_field=200, upload_to='portfolio/images/', width_field=300),
        ),
    ]
